apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kam-d3-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: kam-d3
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: kam-d3-container
        image: kamcicdacr.azurecr.io/datasciencekam/d3:#{Build.BuildId}#
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: kam-d3-service
spec:
  selector:
    app: kam-d3
  type: LoadBalancer
  ports:
  - port: 80
    name: kam-d3-port